### ISSUE TITLE
Rewrite filename fetching logic to work with binaries

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/samosa#2]
**Description:**
After releasing binaries for samosa through GoReleaser and GitHub Releases, the following error occurs on running the binary:

```
2022/03/26 09:38:54 failed to get coverage data: go/build: go list github.com/burntcarrot/samosa/internal/: exit status 2
go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.6/x64
```

**Pointers:**
The point of failure is inside [getFilename](https://github.com/burntcarrot/samosa/blob/main/internal/utils.go#L43). Investigate [getFilename](https://github.com/burntcarrot/samosa/blob/main/internal/utils.go#L43) and rewrite the function.

**Comment by ehrktia** [comment]
thanks @poonai for starring the repo and it showed in my feed all hail github new "For You" feature. @burntcarrot the issue is in the https://github.com/burntcarrot/samosa/blob/main/internal/utils.go#L43 is using static path so when we provide a path to binary is looking in the dependencies. Need to come up with different approach
```golang
func Test_get_file_name(t *testing.T) {
	got,err:=getFilename("github.com/web-alytics/meditate/pkg/logging/logging.go")
	t.Logf("%v\n",got)
	t.Logf("%v\n",err)
}
```

output:
```
dir: github.com/web-alytics/meditate/pkg/logging/
file: logging.go
    utils_test.go:31:
    utils_test.go:32: no required module provides package github.com/web-alytics/meditate/pkg/logging; to add it:
                go get github.com/web-alytics/meditate/pkg/logging
```

**Comment by burntcarrot** [comment]
@ehrktia Thanks for the info! It would be great if you could help by coming up with a fix! ❤️

**Comment by ehrktia** [comment]
> @ehrktia Thanks for the info! It would be great if you could help by coming up with a fix! heart
checking locally will reply back once i have some thing but is a bit tricky to be frank

**Comment by karthick-ayyapillai** [comment]
@burntcarrot can you please try this in your local https://play.golang.com/p/Ksjv3wR3fj8 and build a binary using `go build -o cover` and test the binary with a cover.

**Comment by ehrktia** [comment]
@burntcarrot  this requires a re-think of the existing implementation,  the `build Import` caches the module in the local mod cache. For the existing approach to work, there are few  options 
1. requires the user to check in the coverage.out into their repo so that this can be fetched alongside when importing the module ( not sure on this needs further testing).
2. initialize a new `bufio.Scanner() `and read the coverage file into the scanner, do file data parsing by splitting the data in lines and generate your report (i.e - do not require the use of the cover package).
